data:
  tokenizer_path: "/scratch/nlp_G1/models/tokenizer/gpt-clean-16000.json"
  train_path: "/scratch/nlp_G1/data/train_10M_clean"
  eval_path: "/scratch/nlp_G1/data/dev_clean"
  seq_length: 128
  eval_samples: 8192

model:
  type: "GPT2" # or "GPT2"
  name: "BabyLlama1-Teacher-GPT2-705M-strict"
  hidden_size: 1536
  intermediate_size: 3072 # train.py uses default = 4 * hidden_size 
  n_layer: 24
  n_head: 16 # Change this if you're using GPT2
  resid_pdrop: 0.0 
  attn_pdrop: 0.0
  embd_pdrop: 0.0

training:
  lr: 2.5e-4
  batch_size: 128
  num_epochs: 4
  gradient_accumulation_steps: 16
  warmup_steps: 300
  fp16: True

logging: 
  wandb: True
  project: "babylm-dev"
  output_dir: "/scratch/nlp_G1/models/base_line/"
