data:
  tokenizer_path: "/scratch/nlp_G1/models/tokenizer/gpt-clean-16000.json"
  train_path: "/scratch/nlp_G1/data/train_10M_clean"
  eval_path: "/scratch/nlp_G1/data/dev_clean"
  seq_length: 128
  eval_samples: 8192

model:
  type: "Llama" # or "GPT2"
  name: "Llama-360M-strict"
  hidden_size: 1024
  intermediate_size: 3072
  n_layer: 24
  n_head: 8 # Change this if you're using GPT2

training:
  lr: 3e-4
  batch_size: 128
  num_epochs: 10
  gradient_accumulation_steps: 8
  warmup_steps: 300
  fp16: True

logging: 
  wandb: True
  project: "babylm-dev"
  output_dir: "/scratch/nlp_G1/models/base_line/"
